### ISSUE TITLE
Cannot find text generation instances after running provision script

### ISSUE THREAD

**Issue by Vivihung** [Azure-Samples/papiro#14]
Don't find any Azure text generation service in the resource group created by `provision.ps1`. But it is required in `.env`. Do we miss creating the instance? or what could I have missed?

`.env.example`
![image](https://user-images.githubusercontent.com/4814277/170134847-7bb41a58-3a6f-4eb3-a681-0a3057ddd68b.png)

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. `./provision.ps1 -name <YOUR_APP_NAME> -location westus`
2. Go to Azure portal and looking for resource group (RG) created by the script `<YOUR_APP_NAME>rg`

### Expected/desired behavior
Finding instances with "text generation" type.

These are what I have in the RG
![image](https://user-images.githubusercontent.com/4814277/170133856-0d8226af-ecd9-4682-a486-9398f99e974e.png)

**Comment by Yonet** [comment]
I also see the endpoint information on the [main.bicep here](https://github.com/Azure-Samples/papiro/blob/149923a8b99c67e4d8c2fd80e961b9ac4cecb368/infra/main.bicep#L65). I'm not familiar with how it works. @sethjuarez, are we missing a step?

**Comment by sethjuarez** [comment]
This is something that gets built using a different repo. Added some [documentation](https://github.com/Azure-Samples/papiro#text-generation) for clarification. Feel free to reopen if this is insufficient
