### ISSUE TITLE
Cannot publish app

### ISSUE THREAD

**Issue by Vivihung** [Azure-Samples/papiro#4]
Cannot publish app with the insturctued command 
`./publish.ps1 -name MY_APP_NAME`

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
In PowerShell, run the following commands
1. `./provision.ps1 -name <YOUR_APP_NAME> -location westus2`
2. `./publish.ps1 -name MY_APP_NAME`

### Any log messages given by the failure
![image](https://user-images.githubusercontent.com/4814277/167954247-d80a40a1-768d-4e6c-a17a-0f08ce5d3783.png)

### Expected/desired behavior
The script run without issues

### OS and Version?
Windows 11

**Comment by Vivihung** [comment]
@Yonet, I have a fix here #12.

**Comment by nicholasdbrady** [comment]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/18353756/170176464-828981bb-3680-4571-9565-b91a8db985cc.png">
Having an issue during publish where it hangs upon .zip file creation. Yarn is installed globally

**Comment by Vivihung** [comment]
@nicholasdbrady I notice this symptom after I added Connect-AzAccount in the script. The shell becomes not responsive due to it prompt a page in browser for login. Could you please check your browser to see if it’s the same situation?
